// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2_1/1143609 Production Release
//       HLS date: Wed Nov 13 18:57:31 PST 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: hiva@iron-04
// Generated date: Wed Mar 18 22:52:42 PDT 2026
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model PECore
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , start("start")
   , input_port("input_port")
   , rva_in("rva_in")
   , rva_out("rva_out")
   , act_port("act_port")
   , SC_SRAM_CONFIG("SC_SRAM_CONFIG")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_start_vld("ccs_rtl_SIG_start_vld")
   , ccs_rtl_SIG_start_rdy("ccs_rtl_SIG_start_rdy")
   , ccs_rtl_SIG_start_dat("ccs_rtl_SIG_start_dat")
   , ccs_rtl_SIG_input_port_vld("ccs_rtl_SIG_input_port_vld")
   , ccs_rtl_SIG_input_port_rdy("ccs_rtl_SIG_input_port_rdy")
   , ccs_rtl_SIG_input_port_dat("ccs_rtl_SIG_input_port_dat")
   , ccs_rtl_SIG_rva_in_vld("ccs_rtl_SIG_rva_in_vld")
   , ccs_rtl_SIG_rva_in_rdy("ccs_rtl_SIG_rva_in_rdy")
   , ccs_rtl_SIG_rva_in_dat("ccs_rtl_SIG_rva_in_dat")
   , ccs_rtl_SIG_rva_out_vld("ccs_rtl_SIG_rva_out_vld")
   , ccs_rtl_SIG_rva_out_rdy("ccs_rtl_SIG_rva_out_rdy")
   , ccs_rtl_SIG_rva_out_dat("ccs_rtl_SIG_rva_out_dat")
   , ccs_rtl_SIG_act_port_vld("ccs_rtl_SIG_act_port_vld")
   , ccs_rtl_SIG_act_port_rdy("ccs_rtl_SIG_act_port_rdy")
   , ccs_rtl_SIG_act_port_dat("ccs_rtl_SIG_act_port_dat")
   , ccs_rtl_SIG_SC_SRAM_CONFIG("ccs_rtl_SIG_SC_SRAM_CONFIG")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.start_vld(ccs_rtl_SIG_start_vld);
   ccs_rtl.start_rdy(ccs_rtl_SIG_start_rdy);
   ccs_rtl.start_dat(ccs_rtl_SIG_start_dat);
   ccs_rtl.input_port_vld(ccs_rtl_SIG_input_port_vld);
   ccs_rtl.input_port_rdy(ccs_rtl_SIG_input_port_rdy);
   ccs_rtl.input_port_dat(ccs_rtl_SIG_input_port_dat);
   ccs_rtl.rva_in_vld(ccs_rtl_SIG_rva_in_vld);
   ccs_rtl.rva_in_rdy(ccs_rtl_SIG_rva_in_rdy);
   ccs_rtl.rva_in_dat(ccs_rtl_SIG_rva_in_dat);
   ccs_rtl.rva_out_vld(ccs_rtl_SIG_rva_out_vld);
   ccs_rtl.rva_out_rdy(ccs_rtl_SIG_rva_out_rdy);
   ccs_rtl.rva_out_dat(ccs_rtl_SIG_rva_out_dat);
   ccs_rtl.act_port_vld(ccs_rtl_SIG_act_port_vld);
   ccs_rtl.act_port_rdy(ccs_rtl_SIG_act_port_rdy);
   ccs_rtl.act_port_dat(ccs_rtl_SIG_act_port_dat);
   ccs_rtl.SC_SRAM_CONFIG(ccs_rtl_SIG_SC_SRAM_CONFIG);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << start.Connections::InBlocking_Ports_abs<bool >::vld << ccs_rtl_SIG_start_rdy << start.Connections::InBlocking<bool, Connections::SYN_PORT >::dat << input_port.Connections::InBlocking_Ports_abs<spec::StreamType >::vld << ccs_rtl_SIG_input_port_rdy << input_port.Connections::InBlocking<spec::StreamType, Connections::SYN_PORT >::dat << rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld << ccs_rtl_SIG_rva_in_rdy << rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat << ccs_rtl_SIG_rva_out_vld << rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy << ccs_rtl_SIG_rva_out_dat << ccs_rtl_SIG_act_port_vld << act_port.Connections::OutBlocking_Ports_abs<nvhls::nv_scvector<ac_int<32, true >, 16U > >::rdy << ccs_rtl_SIG_act_port_dat << SC_SRAM_CONFIG;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1705:clk:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1705
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1705; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1706:rst:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1706
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1706; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1706); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1706); // then write to RTL port
   
   // none.sc_in field_key=start:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1712:vld:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1723
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1723; // NPS - LV to hold field
   type_to_vector(start.Connections::InBlocking_Ports_abs<bool >::vld.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1723); // read orig port and type convert
   ccs_rtl_SIG_start_vld.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1723); // then write to RTL port
   
   // none.sc_out field_key=start:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1712:rdy:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1724
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1724;
   bool d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1724;
   t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1724 = ccs_rtl_SIG_start_rdy.read();
   vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1724, 1, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1724);
   start.Connections::InBlocking_Ports_abs<bool >::rdy.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1724);
   
   // none.sc_in field_key=start:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1712:dat:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1725
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1725; // NPS - LV to hold field
   type_to_vector(start.Connections::InBlocking<bool, Connections::SYN_PORT >::dat.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1725); // read orig port and type convert
   ccs_rtl_SIG_start_dat.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1725); // then write to RTL port
   
   // none.sc_in field_key=input_port:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1726:vld:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1735
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1735; // NPS - LV to hold field
   type_to_vector(input_port.Connections::InBlocking_Ports_abs<spec::StreamType >::vld.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1735); // read orig port and type convert
   ccs_rtl_SIG_input_port_vld.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1735); // then write to RTL port
   
   // none.sc_out field_key=input_port:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1726:rdy:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1736
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1736;
   bool d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1736;
   t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1736 = ccs_rtl_SIG_input_port_rdy.read();
   vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1736, 1, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1736);
   input_port.Connections::InBlocking_Ports_abs<spec::StreamType >::rdy.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1736);
   
   // none.sc_in field_key=input_port:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1726:dat:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1737
   sc_lv< 138 > t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1737; // NPS - LV to hold field
   type_to_vector(input_port.Connections::InBlocking<spec::StreamType, Connections::SYN_PORT >::dat.read(),138,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1737); // read orig port and type convert
   ccs_rtl_SIG_input_port_dat.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1737); // then write to RTL port
   
   // none.sc_in field_key=rva_in:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1738:vld:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1747
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1747; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::vld.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1747); // read orig port and type convert
   ccs_rtl_SIG_rva_in_vld.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1747); // then write to RTL port
   
   // none.sc_out field_key=rva_in:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1738:rdy:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1748
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1748;
   bool d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1748;
   t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1748 = ccs_rtl_SIG_rva_in_rdy.read();
   vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1748, 1, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1748);
   rva_in.Connections::InBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Write >::rdy.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1748);
   
   // none.sc_in field_key=rva_in:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1738:dat:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1749
   sc_lv< 169 > t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1749; // NPS - LV to hold field
   type_to_vector(rva_in.Connections::InBlocking<RVSink<spec::Axi::rvaCfg >::Write, Connections::SYN_PORT >::dat.read(),169,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1749); // read orig port and type convert
   ccs_rtl_SIG_rva_in_dat.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1749); // then write to RTL port
   
   // none.sc_out field_key=rva_out:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1750:vld:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1759
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1759;
   bool d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1759;
   t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1759 = ccs_rtl_SIG_rva_out_vld.read();
   vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1759, 1, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1759);
   rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::vld.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1759);
   
   // none.sc_in field_key=rva_out:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1750:rdy:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1760
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1760; // NPS - LV to hold field
   type_to_vector(rva_out.Connections::OutBlocking_Ports_abs<RVSink<spec::Axi::rvaCfg >::Read >::rdy.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1760); // read orig port and type convert
   ccs_rtl_SIG_rva_out_rdy.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1760); // then write to RTL port
   
   // none.sc_out field_key=rva_out:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1750:dat:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1761
   sc_lv< 128 > t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1761;
   sc_dt::sc_lv<128 > d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1761;
   t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1761 = ccs_rtl_SIG_rva_out_dat.read();
   vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1761, 128, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1761);
   rva_out.Connections::OutBlocking<RVSink<spec::Axi::rvaCfg >::Read, Connections::SYN_PORT >::dat.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1761);
   
   // none.sc_out field_key=act_port:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1762:vld:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1771
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1771;
   bool d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1771;
   t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1771 = ccs_rtl_SIG_act_port_vld.read();
   vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1771, 1, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1771);
   act_port.Connections::OutBlocking_Ports_abs<nvhls::nv_scvector<ac_int<32, true >, 16U > >::vld.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1771);
   
   // none.sc_in field_key=act_port:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1762:rdy:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1772
   sc_logic t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1772; // NPS - LV to hold field
   type_to_vector(act_port.Connections::OutBlocking_Ports_abs<nvhls::nv_scvector<ac_int<32, true >, 16U > >::rdy.read(),1,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1772); // read orig port and type convert
   ccs_rtl_SIG_act_port_rdy.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1772); // then write to RTL port
   
   // none.sc_out field_key=act_port:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1762:dat:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1773
   sc_lv< 512 > t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1773;
   sc_dt::sc_lv<512 > d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1773;
   if ( ccs_rtl_SIG_act_port_vld.read() == SC_LOGIC_1 ) {
      t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1773 = ccs_rtl_SIG_act_port_dat.read();
      vector_to_type(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1773, 512, &d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1773);
      act_port.Connections::OutBlocking<nvhls::nv_scvector<ac_int<32, true >, 16U >, Connections::SYN_PORT >::dat.write(d_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1773);
   }
   
   // none.sc_in field_key=SC_SRAM_CONFIG:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1774:SC_SRAM_CONFIG:d66c9ff6-460f-4e88-8385-b754f17bdd5d-1774
   sc_lv< 32 > t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1774; // NPS - LV to hold field
   type_to_vector(SC_SRAM_CONFIG.read(),32,t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1774); // read orig port and type convert
   ccs_rtl_SIG_SC_SRAM_CONFIG.write(t_d66c9ff6_460f_4e88_8385_b754f17bdd5d_1774); // then write to RTL port
}
