directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#1.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:and#1.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#2.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#2.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:and#11.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#2.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#3.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#3.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:and#12.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#3.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:nor.tmp.2 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:nor.tmp.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:and#13.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:nor.tmp.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#11.itm.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#11.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.st.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#11.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(119) REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#7.itm.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#7.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(111) REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#7.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.2 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(103) REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#14.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#14.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-15:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#14.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(79:72).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#14.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(79:72).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#14.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#22.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#14.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#15.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-16:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(87:80).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(87:80).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#24.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#15.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#12.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-13:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(127:120).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(127:120).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#2.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#13.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#13.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-14:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#13.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(71:64).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#13.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(71:64).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#13.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#20.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#13.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#10.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-11:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(111:104).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(111:104).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#16.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#11.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-12:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(119:112).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(119:112).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#18.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#8.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#8.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-9:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#8.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#6.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#8.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#9.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-10:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#8.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#6.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#6.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-7:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#6.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#30.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#6.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#7.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#7.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-8:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#7.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#4.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#7.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#4.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#4.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-5:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#4.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#12.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#4.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(23:17).sva.dfm.2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#4.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#5.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#5.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-6:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#5.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#28.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#5.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#2.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-3:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(95:88).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(95:88).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#26.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#3.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#3.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-4:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#3.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#10.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#3.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(15:9).sva.dfm.2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#3.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks_load_store#1:for:else:mux#1.itm.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/result.val.Marshall<128U>#3:for-2:marshaller.AddField<ac_int<8,false>,8>#23:else:bits:slc(BitsToType<spec::PE::Weight::WordType>#3:marshaller.glob,*1)(7-0).ncse.lpi#1.dfm#2 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(103:96).sva.dfm#4 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(103:96).sva.dfm#4.1 REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h#14.itm.1(13:7) REGISTER_NAME input_mem.banks_load_store#1:for:else:mux#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:unequal.tmp.1 REGISTER_NAME DecodeMXByte:unequal.tmp.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_read_req_valid.lpi#1.dfm#1.2 REGISTER_NAME DecodeMXByte:unequal.tmp.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#14.lpi#1.dfm.1(6:3) REGISTER_NAME DecodeE2M1Fixed#1:result(7:0)#14.lpi#1.dfm.1(6:3)
directive set /PECore/PECore:PECoreRun/PECoreRun/while:if:slc(while:Connections::InBlocking<RVSink<spec::Axi::rvaCfg>::Write,Connections::SYN_PORT>::PopNB(rva_in_reg.addr))(23-4)#3.itm.2 REGISTER_NAME DecodeE2M1Fixed#1:result(7:0)#14.lpi#1.dfm.1(6:3)
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(23) REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(23)
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_in_reg.rw.sva.st.2 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(23)
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#1.lpi#1.dfm.1(2:0) REGISTER_NAME DecodeE2M1Fixed#1:result(7:0)#1.lpi#1.dfm.1(2:0)
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(27:25).sva.dfm.2 REGISTER_NAME DecodeE2M1Fixed#1:result(7:0)#1.lpi#1.dfm.1(2:0)
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(15) REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(15)
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_in_reg.rw.sva.st#1.2 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(15)
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:asn.itm.2 REGISTER_NAME PECore::RunMac:if:for:if:asn.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunScale:if:asn#3.itm.2 REGISTER_NAME PECore::RunMac:if:for:if:asn.itm.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunScale:PECore::RunScale:if:and#1.svs.st.2 REGISTER_NAME PECore::RunScale:PECore::RunScale:if:and#1.svs.st.2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#1.1(127) REGISTER_NAME PECore::RunScale:PECore::RunScale:if:and#1.svs.st.2
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunFSM:switch-lp:equal.tmp#1.1 REGISTER_NAME PECore::RunFSM:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_read_req_valid.lpi#1.dfm#1.1 REGISTER_NAME PECore::RunFSM:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunFSM:switch-lp:nor.tmp.1 REGISTER_NAME PECore::RunFSM:switch-lp:nor.tmp.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_read_req_valid.lpi#1.dfm#1.1 REGISTER_NAME PECore::RunFSM:switch-lp:nor.tmp.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_read_addrs.sva#1.1 REGISTER_NAME input_read_addrs.sva#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(103:96).sva.dfm#2.1 REGISTER_NAME input_read_addrs.sva#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:asn#2.itm.1 REGISTER_NAME DecodeMXByte:asn#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunScale:if:asn#3.itm.1 REGISTER_NAME DecodeMXByte:asn#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(49:48).sva.dfm#1.1 REGISTER_NAME DecodeMXByte:asn#2.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:or#22.itm.1 REGISTER_NAME PECore::UpdateFSM:switch-lp:or#22.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_read_req_valid.lpi#1.dfm#1.st.1 REGISTER_NAME PECore::UpdateFSM:switch-lp:or#22.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:PECore::UpdateFSM:switch-lp:and#12.itm.1 REGISTER_NAME PECore::UpdateFSM:switch-lp:PECore::UpdateFSM:switch-lp:and#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/state(0).sva REGISTER_NAME PECore::UpdateFSM:switch-lp:PECore::UpdateFSM:switch-lp:and#12.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:pe_config.UpdateManagerCounter:nand.itm.1 REGISTER_NAME PECore::UpdateFSM:switch-lp:pe_config.UpdateManagerCounter:nand.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_write_req_valid.lpi#1.dfm#1.st.1 REGISTER_NAME PECore::UpdateFSM:switch-lp:pe_config.UpdateManagerCounter:nand.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:and#10.itm.1 REGISTER_NAME PECore::RunMac:and#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_read_req_valid.lpi#1.dfm#1.2 REGISTER_NAME PECore::RunMac:and#10.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#11.itm.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::PushOutput:PECore::PushOutput:if:and.svs.st.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#11.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:and.stg_1_1.sva.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunScale:PECore::RunScale:if:and#1.svs.st.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#9.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#7.itm.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#7.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.st.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#7.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:PECore::RunMac:if:and.svs.1 REGISTER_NAME PECore::DecodeAxiRead:case-4:switch-lp:PECore::DecodeAxiRead:case-4:switch-lp:and#5.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#3.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#3.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:equal.tmp#2.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#3.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#2.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:and#8.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#2.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:equal.tmp#1.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:case-1:if:PECore::UpdateFSM:case-1:if:and.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_write_req_valid.lpi#1.dfm#1.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_write_req_valid.lpi#1.dfm#3 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_write_req_valid.lpi#1.dfm#1.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:equal.tmp#1.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::DecodeAxiRead:switch-lp:nor.tmp.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:nor.tmp.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::UpdateFSM:switch-lp:nor#7.itm.1 REGISTER_NAME PECore::DecodeAxiRead:switch-lp:nor.tmp.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:and.stg_1_0.sva.1 REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_0.sva.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_in_reg.rw.sva.1 REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_0.sva.1
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:slc(mac_read_chunk)(1)#1.itm.1 REGISTER_NAME PECore::RunMac:if:for:if:slc(mac_read_chunk)(1)#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(56).sva.dfm#2.1 REGISTER_NAME PECore::RunMac:if:for:if:slc(mac_read_chunk)(1)#1.itm.1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read#1:read_data.lpi#1.dfm#2 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.banks.read:read_data.lpi#1.dfm#1 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#2
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.banks.read:read_data.lpi#1.dfm#1 REGISTER_NAME input_mem.banks.read#1:read_data.lpi#1.dfm#2
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm#1 REGISTER_NAME input_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm#1
directive set /PECore/PECore:PECoreRun/PECoreRun/input_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm.1 REGISTER_NAME input_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm#1
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:DecodeMXByte:mux1h.itm.1(13:7) REGISTER_NAME input_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm#1
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm REGISTER_NAME weight_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm
directive set /PECore/PECore:PECoreRun/PECoreRun/weight_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm.1 REGISTER_NAME weight_mem.run#3:port_read_out_local.data(0)(0).lpi#1.dfm
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(35:32).sva.dfm#4 REGISTER_NAME rva_out_reg.data(35:32).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(35:32).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(35:32).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#1.lpi#1.dfm.1(6:3) REGISTER_NAME rva_out_reg.data(35:32).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(39:36).sva.dfm#4 REGISTER_NAME rva_out_reg.data(39:36).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(39:36).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(39:36).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#10.lpi#1.dfm.1(6:3) REGISTER_NAME rva_out_reg.data(39:36).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(43:40).sva.dfm#4 REGISTER_NAME rva_out_reg.data(43:40).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(43:40).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(43:40).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#11.lpi#1.dfm.1(6:3) REGISTER_NAME rva_out_reg.data(43:40).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(47:44).sva.dfm#4 REGISTER_NAME rva_out_reg.data(47:44).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(47:44).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(47:44).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#12.lpi#1.dfm.1(6:3) REGISTER_NAME rva_out_reg.data(47:44).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(49:48).sva.dfm#4 REGISTER_NAME rva_out_reg.data(49:48).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(49:48).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(49:48).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeMXByte:asn#2.itm.2 REGISTER_NAME rva_out_reg.data(49:48).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(55:50).sva.dfm#4 REGISTER_NAME rva_out_reg.data(55:50).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(55:50).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(55:50).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#11.lpi#1.dfm.1(2:0) REGISTER_NAME rva_out_reg.data(55:50).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(56).sva.dfm#4 REGISTER_NAME rva_out_reg.data(56).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(56).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(56).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::PushOutput:PECore::PushOutput:if:and.svs.st.2 REGISTER_NAME rva_out_reg.data(56).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(59:57).sva.dfm#4 REGISTER_NAME rva_out_reg.data(59:57).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(59:57).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(59:57).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#10.lpi#1.dfm.1(2:0) REGISTER_NAME rva_out_reg.data(59:57).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(63:60).sva.dfm#4 REGISTER_NAME rva_out_reg.data(63:60).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_out_reg.data(63:60).sva.dfm#4.1 REGISTER_NAME rva_out_reg.data(63:60).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/DecodeE2M1Fixed#1:result(7:0)#13.lpi#1.dfm.1(6:3) REGISTER_NAME rva_out_reg.data(63:60).sva.dfm#4
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:and.stg_1_2.sva REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_2.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:not.itm.1 REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_2.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_in_reg.rw.sva.st#1.1 REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_2.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:and.stg_1_3.sva REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_3.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/PECore::RunMac:if:for:if:slc(mac_read_chunk)(0).itm.1 REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_3.sva
directive set /PECore/PECore:PECoreRun/PECoreRun/rva_in_reg.rw.sva.st.1 REGISTER_NAME PECore::RunMac:if:for:if:and.stg_1_3.sva
